### ISSUE TITLE
Codepoints

### ISSUE THREAD

**Issue by easrng** [noahsark769/sfsymbols.com#11]
I would really appreciate if this site showed the unicode characters for the icons in the SF Symbols font. Are there any other resources that have the codepoints?

**Comment by noahsark769** [comment]
Hi @easrng, so sorry in the delay in getting back to you. I'm not aware of any other websites that show the unicode codepoints for the symbol characters. @aaronpearce has an example app which shows the codepoints, but you'll have to compile it yourself I'm afraid, since it was removed from the app store due to licensing issues (same reason sfsymbols.com doesn't show the symbol images). Here's the repo, hope it helps! https://github.com/aaronpearce/SF-Viewer
